name: Auto Comment on PR

on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const commentBody = `### Thank you for your pull request! 😊
            We’ll review it promptly. Please verify the file changes and ensure all commits are correct. If there are any unresolved review comments, kindly address them.
            Don’t forget to ⭐ star the repository if you find it helpful – it means a lot to the project!`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
            console.log('Comment added successfully.');

